export type Gender = 'Male' | 'Female' | 'Kids' | 'Unisex';
export type DayNight = 'Day' | 'Night' | 'Both';
export type Season = 'Winter' | 'Spring' | 'Summer' | 'Autumn';
export type Category = 'Perfume' | 'Brand Perfume' | 'Luxury Perfume';
export type StockStatus = 'In Stock' | 'Low Stock' | 'Out Stock';

export interface Perfume {
  id: string;
  name: string;
  code: string;
  brand: string;
  price: number;
  gender: Gender;
  category: Category;
  stockStatus: StockStatus;
  description: string;
  rating: number;
  mainImage: string;
  miniImage?: string;
  galleryImages: string[];
  accords: { name: string; value: number; color: string }[];
  fragranceProfile: {
    longevity: string;
    projection: string;
    sillage: string;
  };
  dayNight: DayNight;
  seasons: Season[];
  notes: {
    top: { name: string; iconUrl: string }[];
    middle: { name: string; iconUrl: string }[];
    base: { name: string; iconUrl: string }[];
  };
}

export const PERFUME_IMAGES = {
  luxuryBlack: '/images/perfumes/luxury-black.jpg',
  luxuryRed: '/images/perfumes/luxury-red.jpg',
  pink: '/images/perfumes/pink.jpg',
  purple: '/images/perfumes/purple.jpg',
  green: '/images/perfumes/green.jpg',
  normal: '/images/perfumes/normal.jpg',
  blue: '/images/perfumes/blue.jpg',
  tan: '/images/perfumes/tan.jpg',
} as const;

const STANDARD_BOTTLES = [
  PERFUME_IMAGES.purple,
  PERFUME_IMAGES.green,
  PERFUME_IMAGES.normal,
  PERFUME_IMAGES.blue,
  PERFUME_IMAGES.tan,
];

// Feminine bottles: pink + purple from the Lumier bottle photo set
const FEMALE_BOTTLES = [
  PERFUME_IMAGES.pink,
  PERFUME_IMAGES.purple,
];

// Neutral bottles shared by everyone: clear, gold and green from the photo set
const UNISEX_BOTTLES = [
  PERFUME_IMAGES.normal,
  PERFUME_IMAGES.tan,
  PERFUME_IMAGES.green,
];

const DEFAULT_IMAGE = PERFUME_IMAGES.normal;

function bottleIndexFromCode(code: string, count: number): number {
  return code.split('').reduce((sum, char) => sum + char.charCodeAt(0), 0) % count;
}

function getPerfumeImage(seed: PerfumeSeed): string {
  const category = seed.category ?? 'Brand Perfume';
  const gender = seed.gender ?? 'Male';

  if (category === 'Luxury Perfume') {
    const useRed = bottleIndexFromCode(seed.code, 2) === 0;
    return useRed ? PERFUME_IMAGES.luxuryRed : PERFUME_IMAGES.luxuryBlack;
  }

  if (gender === 'Female') {
    return FEMALE_BOTTLES[bottleIndexFromCode(seed.code, FEMALE_BOTTLES.length)];
  }

  if (gender === 'Unisex') {
    return UNISEX_BOTTLES[bottleIndexFromCode(seed.code, UNISEX_BOTTLES.length)];
  }

  return STANDARD_BOTTLES[bottleIndexFromCode(seed.code, STANDARD_BOTTLES.length)];
}

const NOTE_ICON =
  'https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=100&h=100&fit=crop';

const ACCORD_COLORS: Record<string, string> = {
  Amber: '#d99e4c',
  Aquatic: '#0ea5e9',
  Aromatic: '#16a6a6',
  Citrus: '#facc15',
  Earthy: '#5c4033',
  Floral: '#d946ef',
  Fresh: '#38bdf8',
  'Fresh Spicy': '#16a6a6',
  Fruity: '#f43f5e',
  Green: '#22c55e',
  Herbal: '#4d7c0f',
  Almond: '#d6a15d',
  Animalic: '#57534e',
  Bourbon: '#92400e',
  Cacao: '#713f12',
  Caramel: '#c2410c',
  Coconut: '#f5f5f4',
  Coffee: '#422006',
  Honey: '#f59e0b',
  Iris: '#8b5cf6',
  Lavender: '#a78bfa',
  Leather: '#1a4aa6',
  Marine: '#0284c7',
  Mineral: '#64748b',
  Mossy: '#365314',
  Musky: '#9ca3af',
  Nutty: '#92400e',
  Ozonic: '#67e8f9',
  Powdery: '#fce7f3',
  Smoky: '#4b5563',
  Sweet: '#ec4899',
  Tobacco: '#78350f',
  Tropical: '#fb923c',
  Vanilla: '#fcd34d',
  Violet: '#7c3aed',
  Vodka: '#94a3b8',
  'Warm Spicy': '#8b4513',
  'White Floral': '#f8fafc',
  Woody: '#a16207',
};

type PerfumeSeed = {
  code: string;
  name: string;
  brand: string;
  category?: Category;
  price?: number;
  gender?: Gender;
  stockStatus?: StockStatus;
  accords: string[];
  top: string[];
  middle: string[];
  base: string[];
  longevity: string;
  sillage: string;
  dayNight: DayNight;
  seasons: Season[];
};

function makeNotes(names: string[]) {
  return names.map((name) => ({ name, iconUrl: NOTE_ICON }));
}

function makeAccords(names: string[]) {
  return names.map((name, index) => ({
    name,
    value: Math.max(55, 95 - index * 10),
    color: ACCORD_COLORS[name] || '#64748b',
  }));
}

function makePerfume(seed: PerfumeSeed): Perfume {
  const notesText = [
    `top notes of ${seed.top.join(', ')}`,
    `heart notes of ${seed.middle.join(', ')}`,
    `base notes of ${seed.base.join(', ')}`,
  ].join('; ');

  const genderLabel =
    seed.gender === 'Female' ? "women's" : seed.gender === 'Unisex' ? 'unisex' : "men's";

  return {
    id: seed.code.toLowerCase(),
    name: seed.name,
    code: seed.code,
    brand: seed.brand,
    price: seed.price ?? 0,
    gender: seed.gender ?? 'Male',
    category: seed.category ?? 'Brand Perfume',
    stockStatus: seed.stockStatus ?? 'In Stock',
    description: `${seed.name} by ${seed.brand} is a ${genderLabel} fragrance built around ${seed.accords.join(', ')} accords, with ${notesText}.`,
    rating: 4.8,
    mainImage: getPerfumeImage(seed),
    galleryImages: [getPerfumeImage(seed)],
    accords: makeAccords(seed.accords),
    fragranceProfile: {
      longevity: seed.longevity,
      projection: seed.sillage,
      sillage: seed.sillage,
    },
    dayNight: seed.dayNight,
    seasons: seed.seasons,
    notes: {
      top: makeNotes(seed.top),
      middle: makeNotes(seed.middle),
      base: makeNotes(seed.base),
    },
  };
}

export const MOCK_PERFUMES: Perfume[] = [
  makePerfume({
    code: 'M01',
    name: 'Aventus Absolu',
    brand: 'Creed',
    category: 'Luxury Perfume',
    accords: ['Warm Spicy', 'Citrus', 'Woody', 'Fruity', 'Aromatic'],
    top: ['Grapefruit', 'Bergamot', 'Black Currant', 'Pink Pepper'],
    middle: ['Ginger', 'Cinnamon', 'Cardamom', 'Patchouli'],
    base: ['Ambroxan', 'Vetiver', 'Labdanum', 'Musk'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter', 'Spring'],
  }),
  makePerfume({
    code: 'M02',
    name: 'Bleu de Chanel',
    brand: 'Chanel',
    accords: ['Citrus', 'Woody', 'Warm Spicy', 'Aromatic', 'Fresh'],
    top: ['Grapefruit', 'Lemon', 'Mint', 'Pink Pepper'],
    middle: ['Ginger', 'Nutmeg', 'Jasmine', 'Iso E Super'],
    base: ['Incense', 'Vetiver', 'Cedar', 'Sandalwood', 'Patchouli', 'White Musk'],
    longevity: '7-9 hours',
    sillage: 'Moderate',
    dayNight: 'Both',
    seasons: ['Spring', 'Summer', 'Autumn'],
  }),
  makePerfume({
    code: 'M03',
    name: 'Sauvage',
    brand: 'Dior',
    accords: ['Fresh Spicy', 'Amber', 'Citrus', 'Aromatic', 'Musky'],
    top: ['Calabrian Bergamot', 'Pepper'],
    middle: ['Sichuan Pepper', 'Lavender', 'Pink Pepper', 'Vetiver', 'Patchouli', 'Geranium'],
    base: ['Ambroxan', 'Cedar', 'Labdanum'],
    longevity: '8-10 hours',
    sillage: 'Enormous',
    dayNight: 'Both',
    seasons: ['Spring', 'Summer', 'Autumn'],
  }),
  makePerfume({
    code: 'M04',
    name: 'Acqua di Gio Profumo',
    brand: 'Giorgio Armani',
    accords: ['Aromatic', 'Marine', 'Fresh Spicy', 'Smoky', 'Woody'],
    top: ['Sea Notes', 'Bergamot'],
    middle: ['Rosemary', 'Sage', 'Geranium'],
    base: ['Incense', 'Patchouli'],
    longevity: '8-10 hours',
    sillage: 'Moderate to Strong',
    dayNight: 'Both',
    seasons: ['Spring', 'Summer', 'Autumn'],
  }),
  makePerfume({
    code: 'M05',
    name: 'Althair',
    brand: 'Parfums de Marly',
    category: 'Luxury Perfume',
    accords: ['Vanilla', 'Warm Spicy', 'Sweet', 'Woody', 'Citrus'],
    top: ['Cinnamon', 'Cardamom', 'Orange Blossom', 'Bergamot'],
    middle: ['Bourbon Vanilla', 'Elemi'],
    base: ['Praline', 'Musk', 'Ambrosia', 'Guaiac Wood'],
    longevity: '10+ hours',
    sillage: 'Strong',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'M06',
    name: 'Tygar',
    brand: 'Bvlgari Le Gemme',
    category: 'Luxury Perfume',
    accords: ['Citrus', 'Amber', 'Woody', 'Fresh Spicy'],
    top: ['Grapefruit'],
    middle: ['Ginger', 'Woodsy Notes'],
    base: ['Ambroxan'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Day',
    seasons: ['Spring', 'Summer'],
  }),
  makePerfume({
    code: 'M07',
    name: 'Platinum Egoiste',
    brand: 'Chanel',
    accords: ['Aromatic', 'Fresh Spicy', 'Herbal', 'Woody', 'Floral'],
    top: ['Lavender', 'Rosemary', 'Neroli', 'Petitgrain'],
    middle: ['Geranium', 'Clary Sage', 'Galbanum', 'Jasmine'],
    base: ['Oakmoss', 'Vetiver', 'Cedar', 'Sandalwood', 'Amber'],
    longevity: '7-8 hours',
    sillage: 'Moderate',
    dayNight: 'Day',
    seasons: ['Spring', 'Summer'],
  }),
  makePerfume({
    code: 'M08',
    name: 'Dior Homme Intense',
    brand: 'Dior',
    category: 'Luxury Perfume',
    accords: ['Iris', 'Woody', 'Earthy', 'Powdery', 'Violet'],
    top: ['Lavender'],
    middle: ['Iris', 'Ambrette (Musk Mallow)', 'Pear'],
    base: ['Virginia Cedar', 'Vetiver'],
    longevity: '10+ hours',
    sillage: 'Strong',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'M09',
    name: 'Voyage',
    brand: 'Nautica',
    accords: ['Green', 'Aquatic', 'Fruity', 'Floral', 'Fresh'],
    top: ['Green Leaves', 'Apple'],
    middle: ['Lotus', 'Mimosa'],
    base: ['Musk', 'Cedar', 'Oakmoss', 'Amber'],
    longevity: '5-6 hours',
    sillage: 'Moderate',
    dayNight: 'Day',
    seasons: ['Spring', 'Summer'],
  }),
  makePerfume({
    code: 'M10',
    name: 'Silver Scent',
    brand: 'Jacques Bogart',
    accords: ['Sweet', 'White Floral', 'Citrus', 'Aromatic', 'Fresh Spicy'],
    top: ['Orange Blossom', 'Lemon'],
    middle: ['Lavender', 'Cardamom', 'Nutmeg', 'Coriander', 'Rosemary', 'Geranium'],
    base: ['Tonka Bean', 'Litchi', 'Teak Wood', 'Vetiver'],
    longevity: '9-10 hours',
    sillage: 'Enormous',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'M11',
    name: 'Fahrenheit',
    brand: 'Dior',
    accords: ['Leather', 'Woody', 'Ozonic', 'Fresh Spicy', 'Citrus'],
    top: ['Nutmeg Flower', 'Lavender', 'Cedar', 'Chamomile', 'Mandarin Orange', 'Bergamot'],
    middle: ['Violet Leaf', 'Nutmeg', 'Cedar', 'Sandalwood', 'Honeysuckle', 'Carnation'],
    base: ['Leather', 'Vetiver', 'Musk', 'Amber', 'Patchouli', 'Tonka Bean'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'M12',
    name: '212 VIP Men',
    brand: 'Carolina Herrera',
    accords: ['Vodka', 'Tropical', 'Fresh Spicy', 'Woody', 'Leather'],
    top: ['Passionfruit', 'Lime', 'Pepper', 'Ginger'],
    middle: ['Vodka', 'Gin', 'Mint', 'Spices'],
    base: ['Amber', 'Leather', 'Woodsy Notes'],
    longevity: '6-8 hours',
    sillage: 'Strong',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'M13',
    name: 'Stronger With You Intensely',
    brand: 'Emporio Armani',
    accords: ['Sweet', 'Vanilla', 'Warm Spicy', 'Amber', 'Nutty'],
    top: ['Pink Pepper', 'Juniper', 'Violet Leaf'],
    middle: ['Toffee', 'Cinnamon', 'Lavender', 'Sage'],
    base: ['Vanilla', 'Tonka Bean', 'Amber', 'Suede'],
    longevity: '9-11 hours',
    sillage: 'Strong',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'M14',
    name: 'Stronger With You',
    brand: 'Emporio Armani',
    accords: ['Sweet', 'Aromatic', 'Warm Spicy', 'Vanilla', 'Nutty'],
    top: ['Cardamom', 'Pink Pepper', 'Violet Leaf', 'Mint'],
    middle: ['Pineapple', 'Cinnamon', 'Melon', 'Sage', 'Lavender'],
    base: ['Vanilla', 'Chestnut', 'Amberwood', 'Cedar', 'Guaiac Wood'],
    longevity: '7-8 hours',
    sillage: 'Moderate to Strong',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'M15',
    name: 'One Million Elixir',
    brand: 'Paco Rabanne',
    accords: ['Sweet', 'Vanilla', 'Fruity', 'Amber', 'Woody'],
    top: ['Apple', 'Davana'],
    middle: ['Damask Rose', 'Cedar', 'Osmanthus'],
    base: ['Vanilla Absolute', 'Tonka Bean', 'Patchouli'],
    longevity: '10+ hours',
    sillage: 'Enormous',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'M16',
    name: 'Eros',
    brand: 'Versace',
    accords: ['Vanilla', 'Aromatic', 'Green', 'Fresh Spicy', 'Citrus'],
    top: ['Mint', 'Green Apple', 'Lemon'],
    middle: ['Tonka Bean', 'Ambroxan', 'Geranium'],
    base: ['Madagascar Vanilla', 'Virginian Cedar', 'Atlas Cedar', 'Vetiver', 'Oakmoss'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter', 'Spring'],
  }),
  makePerfume({
    code: 'M17',
    name: 'The One (EDP)',
    brand: 'Dolce & Gabbana',
    accords: ['Amber', 'Warm Spicy', 'Tobacco', 'Citrus', 'Aromatic'],
    top: ['Grapefruit', 'Coriander', 'Basil'],
    middle: ['Ginger', 'Cardamom', 'Orange Blossom'],
    base: ['Amber', 'Tobacco', 'Cedar'],
    longevity: '6-7 hours',
    sillage: 'Moderate',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'M18',
    name: 'The Most Wanted',
    brand: 'Azzaro',
    accords: ['Sweet', 'Amber', 'Warm Spicy', 'Woody'],
    top: ['Cardamom'],
    middle: ['Toffee / Caramel'],
    base: ['Amberwood'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'M19',
    name: 'Y Eau de Parfum',
    brand: 'Yves Saint Laurent',
    accords: ['Aromatic', 'Woody', 'Fresh Spicy', 'Herbal', 'Citrus'],
    top: ['Apple', 'Ginger', 'Bergamot'],
    middle: ['Sage', 'Juniper Berries', 'Geranium'],
    base: ['Amberwood', 'Tonka Bean', 'Cedar', 'Vetiver', 'Olibanum'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Spring', 'Summer', 'Autumn'],
  }),
  makePerfume({
    code: 'M20',
    name: 'Stronger Power',
    brand: 'Custom / Inspired Profile',
    category: 'Perfume',
    accords: ['Fresh Spicy', 'Woody', 'Citrus', 'Amber'],
    top: ['Bergamot', 'Cardamom', 'Lemon'],
    middle: ['Lavender', 'Pink Pepper', 'Geranium'],
    base: ['Cedarwood', 'Amberwood', 'Patchouli', 'Tonka'],
    longevity: '7-8 hours',
    sillage: 'Moderate',
    dayNight: 'Day',
    seasons: ['Spring', 'Autumn'],
  }),
  makePerfume({
    code: 'M21',
    name: 'Legend Blue',
    brand: 'Montblanc',
    accords: ['Aromatic', 'Fresh Spicy', 'Woody', 'Lavender'],
    top: ['Spearmint', 'Lavender'],
    middle: ['Cedarwood', 'Sandalwood'],
    base: ['Ambrosia', 'Moss'],
    longevity: '6-7 hours',
    sillage: 'Moderate',
    dayNight: 'Day',
    seasons: ['Spring', 'Summer'],
  }),
  makePerfume({
    code: 'M22',
    name: 'Wanted',
    brand: 'Azzaro',
    accords: ['Citrus', 'Warm Spicy', 'Aromatic', 'Woody', 'Amber'],
    top: ['Lemon', 'Ginger', 'Lavender', 'Mint'],
    middle: ['Guatemalan Cardamom', 'Juniper', 'Apple', 'Geranium'],
    base: ['Haitian Vetiver', 'Tonka Bean', 'Amberwood'],
    longevity: '7-8 hours',
    sillage: 'Strong',
    dayNight: 'Day',
    seasons: ['Spring', 'Autumn'],
  }),
  makePerfume({
    code: 'M23',
    name: 'Aventus',
    brand: 'Creed',
    category: 'Luxury Perfume',
    accords: ['Fruity', 'Woody', 'Smoky', 'Citrus', 'Leather'],
    top: ['Pineapple', 'Bergamot', 'Black Currant', 'Apple'],
    middle: ['Birch', 'Patchouli', 'Moroccan Jasmine', 'Rose'],
    base: ['Musk', 'Oakmoss', 'Ambergris', 'Vanille'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Spring', 'Summer', 'Autumn'],
  }),
  makePerfume({
    code: 'W40',
    name: 'Flora',
    brand: 'Gucci',
    gender: 'Female',
    accords: ['Floral', 'Citrus', 'Fresh', 'Fruity', 'Rose'],
    top: ['Peony', 'Citrus', 'Mandarin Orange'],
    middle: ['Rose', 'Osmanthus'],
    base: ['Sandalwood', 'Patchouli', 'Pink Pepper'],
    longevity: '6-8 hours',
    sillage: 'Moderate',
    dayNight: 'Day',
    seasons: ['Spring', 'Summer'],
  }),
  makePerfume({
    code: 'W41',
    name: 'Burberry Her',
    brand: 'Burberry',
    gender: 'Female',
    accords: ['Fruity', 'Sweet', 'Woody', 'Musky', 'Powdery'],
    top: ['Strawberry', 'Raspberry', 'Blackberry', 'Sour Cherry', 'Black Currant'],
    middle: ['Jasmine', 'Violet'],
    base: ['Musk', 'Vanilla', 'Cashmeran', 'Woody Notes', 'Amber', 'Oakmoss'],
    longevity: '7-9 hours',
    sillage: 'Moderate to Strong',
    dayNight: 'Day',
    seasons: ['Spring', 'Autumn'],
  }),
  makePerfume({
    code: 'W42',
    name: 'Coco Mademoiselle',
    brand: 'Chanel',
    gender: 'Female',
    accords: ['Citrus', 'Woody', 'Patchouli', 'Sweet', 'White Floral'],
    top: ['Orange', 'Mandarin Orange', 'Bergamot', 'Orange Blossom'],
    middle: ['Turkish Rose', 'Jasmine', 'Mimosa', 'Ylang-Ylang'],
    base: ['Patchouli', 'White Musk', 'Vanilla', 'Vetiver', 'Tonka Bean', 'Opoponax'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Spring', 'Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'W43',
    name: "J'adore",
    brand: 'Dior',
    gender: 'Female',
    accords: ['White Floral', 'Floral', 'Fruity', 'Sweet', 'Aquatic'],
    top: ['Pear', 'Melon', 'Magnolia', 'Peach', 'Mandarin Orange', 'Bergamot'],
    middle: ['Jasmine', 'Lily-of-the-Valley', 'Tuberose', 'Freesia', 'Rose', 'Orchid', 'Plum', 'Violet'],
    base: ['Musk', 'Vanilla', 'Blackberry', 'Cedar'],
    longevity: '7-8 hours',
    sillage: 'Moderate',
    dayNight: 'Day',
    seasons: ['Spring', 'Summer'],
  }),
  makePerfume({
    code: 'W44',
    name: 'My Way',
    brand: 'Giorgio Armani',
    gender: 'Female',
    accords: ['White Floral', 'Tuberose', 'Citrus', 'Animalic', 'Powdery'],
    top: ['Orange Blossom', 'Bergamot'],
    middle: ['Tuberose', 'Indian Jasmine'],
    base: ['Madagascar Vanilla', 'White Musk', 'Virginian Cedar'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Day',
    seasons: ['Spring', 'Summer', 'Autumn'],
  }),
  makePerfume({
    code: 'W45',
    name: 'Libre',
    brand: 'Yves Saint Laurent',
    gender: 'Female',
    accords: ['Lavender', 'Citrus', 'White Floral', 'Sweet', 'Aromatic'],
    top: ['Lavender', 'Mandarin Orange', 'Black Currant', 'Petitgrain'],
    middle: ['Lavender', 'Orange Blossom', 'Jasmine'],
    base: ['Madagascar Vanilla', 'Musk', 'Cedar', 'Ambergris'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Autumn', 'Spring'],
  }),
  makePerfume({
    code: 'W46',
    name: 'Power of You',
    brand: 'Emporio Armani (You Series)',
    gender: 'Female',
    accords: ['Sweet', 'Vanilla', 'Amber', 'Fruity', 'Warm Spicy'],
    top: ['Cherry', 'Bergamot', 'Pink Pepper'],
    middle: ['Jasmine', 'Rose', 'Orange Blossom'],
    base: ['Bourbon Vanilla', 'Amber', 'Tonka Bean'],
    longevity: '7-8 hours',
    sillage: 'Moderate',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'W47',
    name: 'Crystal Noir',
    brand: 'Versace',
    gender: 'Female',
    accords: ['Warm Spicy', 'Coconut', 'White Floral', 'Fresh Spicy', 'Woody'],
    top: ['Pepper', 'Ginger', 'Cardamom'],
    middle: ['Coconut', 'Gardenia', 'Orange Blossom', 'Peony'],
    base: ['Sandalwood', 'Musk', 'Amber'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'W48',
    name: 'Donna Extra Dose',
    brand: 'Valentino (Born in Roma Extra Dose Profile)',
    gender: 'Female',
    accords: ['Vanilla', 'Bourbon', 'Woody', 'White Floral', 'Sweet'],
    top: ['Black Currant', 'Bergamot'],
    middle: ['Jasmine', 'Jasmine Sambac'],
    base: ['Bourbon Vanilla', 'Cashmeran', 'Guaiac Wood'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'W49',
    name: 'Good Girl',
    brand: 'Carolina Herrera',
    gender: 'Female',
    accords: ['Sweet', 'White Floral', 'Warm Spicy', 'Vanilla', 'Cacao'],
    top: ['Almond', 'Coffee', 'Bergamot', 'Lemon'],
    middle: ['Tuberose', 'Jasmine Sambac', 'Orange Blossom', 'Orris', 'Bulgarian Rose'],
    base: ['Tonka Bean', 'Cacao', 'Vanilla', 'Praline', 'Sandalwood', 'Amber', 'Musk', 'Cashmere Wood', 'Cinnamon', 'Patchouli', 'Cedar'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'W50',
    name: 'Escada Magnetism',
    brand: 'Escada',
    gender: 'Female',
    accords: ['Sweet', 'Fruity', 'Caramel', 'Amber', 'Green'],
    top: ['Red Berries', 'Black Currant', 'Cassia', 'Litchi', 'Pineapple', 'Melon'],
    middle: ['Green Leaves', 'Basil', 'Almond Blossom', 'Iris', 'Freesia', 'Heliotrope', 'Jasmine', 'Rose', 'Caraway', 'Lily-of-the-Valley', 'Magnolia'],
    base: ['Caramel', 'Vanilla', 'Amber', 'Coconut', 'Unrefined Sugar', 'Benzoin', 'Sandalwood', 'Musk', 'Patchouli', 'Vetiver'],
    longevity: '7-9 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'W51',
    name: 'Bombshell',
    brand: "Victoria's Secret",
    gender: 'Female',
    accords: ['Fruity', 'Sweet', 'Citrus', 'Floral', 'Fresh'],
    top: ['Passionfruit', 'Grapefruit', 'Pineapple', 'Tangerine', 'Big Strawberry'],
    middle: ['Peony', 'Vanilla Orchid', 'Red Berries', 'Jasmine', 'Lily-of-the-Valley'],
    base: ['Musk', 'Woody Notes', 'Oakmoss'],
    longevity: '5-6 hours',
    sillage: 'Moderate',
    dayNight: 'Day',
    seasons: ['Spring', 'Summer'],
  }),
  makePerfume({
    code: 'W52',
    name: 'Si Red Musk (Si Passione Red Musk)',
    brand: 'Giorgio Armani',
    gender: 'Female',
    accords: ['Fruity', 'Musky', 'Rose', 'Vanilla', 'Woody'],
    top: ['Black Currant', 'Pink Pepper', 'Pear'],
    middle: ['Rose', 'Jasmine', 'Heliotrope'],
    base: ['White Musk', 'Vanilla', 'Cedarwood'],
    longevity: '7-8 hours',
    sillage: 'Moderate',
    dayNight: 'Both',
    seasons: ['Autumn', 'Spring'],
  }),
  makePerfume({
    code: 'W53',
    name: 'Le Parfum',
    brand: 'Elie Saab',
    gender: 'Female',
    accords: ['White Floral', 'Honey', 'Sweet', 'Floral', 'Citrus'],
    top: ['African Orange Flower'],
    middle: ['Jasmine'],
    base: ['Honey', 'Patchouli', 'Rose', 'Virginia Cedar'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Spring', 'Autumn'],
  }),
  makePerfume({
    code: 'W54',
    name: 'Gucci Bloom',
    brand: 'Gucci',
    gender: 'Female',
    accords: ['White Floral', 'Tuberose', 'Powdery', 'Floral'],
    top: ['Jasmine'],
    middle: ['Tuberose'],
    base: ['Rangoon Creeper'],
    longevity: '7-8 hours',
    sillage: 'Moderate to Strong',
    dayNight: 'Day',
    seasons: ['Spring', 'Summer'],
  }),
  makePerfume({
    code: 'W55',
    name: 'Miami Blossom',
    brand: 'Escada',
    gender: 'Female',
    accords: ['Sweet', 'Tropical', 'Fruity', 'Citrus', 'Fresh'],
    top: ['Watermelon', 'Orange', 'Blueberry'],
    middle: ['Pineapple', 'Tuberose', 'Jasmine', 'Tiare Flower'],
    base: ['Ambroxan', 'Musk', 'Sandalwood'],
    longevity: '5-6 hours',
    sillage: 'Moderate',
    dayNight: 'Day',
    seasons: ['Summer'],
  }),
  makePerfume({
    code: 'W56',
    name: 'Girl of Now',
    brand: 'Elie Saab',
    gender: 'Female',
    accords: ['Nutty', 'Sweet', 'Almond', 'Fruity', 'Woody'],
    top: ['Pistachio', 'Pear', 'Mandarin Orange'],
    middle: ['Almond', 'Orange Blossom', 'Magnolia'],
    base: ['Almond Milk', 'Tonka Bean', 'Cashmeran', 'Patchouli'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'W57',
    name: 'La Vie Est Belle',
    brand: 'Lancome',
    gender: 'Female',
    accords: ['Sweet', 'Vanilla', 'Fruity', 'Powdery', 'Patchouli'],
    top: ['Black Currant', 'Pear'],
    middle: ['Iris', 'Jasmine', 'Orange Blossom'],
    base: ['Praline', 'Vanilla', 'Patchouli', 'Tonka Bean'],
    longevity: '10+ hours',
    sillage: 'Enormous',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'W58',
    name: 'Scandal',
    brand: 'Jean Paul Gaultier',
    gender: 'Female',
    accords: ['Honey', 'Sweet', 'White Floral', 'Citrus', 'Caramel'],
    top: ['Blood Orange', 'Mandarin Orange'],
    middle: ['Honey', 'Gardenia', 'Orange Blossom', 'Jasmine', 'Peach'],
    base: ['Beeswax', 'Caramel', 'Patchouli', 'Licorice'],
    longevity: '9-11 hours',
    sillage: 'Strong',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'W59',
    name: 'Si',
    brand: 'Giorgio Armani',
    gender: 'Female',
    accords: ['Fruity', 'Woody', 'Vanilla', 'Aromatic', 'Soft Spicy'],
    top: ['Cassis (Black Currant Nectar)'],
    middle: ['May Rose', 'Freesia'],
    base: ['Vanilla', 'Patchouli', 'Woody Notes', 'Ambroxan'],
    longevity: '8-9 hours',
    sillage: 'Moderate',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter', 'Spring'],
  }),
  makePerfume({
    code: 'W60',
    name: 'For Her Eau de Toilette (Black Bottle)',
    brand: 'Narciso Rodriguez',
    gender: 'Female',
    accords: ['Musky', 'White Floral', 'Powdery', 'Citrus', 'Floral'],
    top: ['African Orange Flower', 'Osmanthus', 'Bergamot'],
    middle: ['Musk', 'Amber'],
    base: ['Vetiver', 'Vanilla', 'Patchouli'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Autumn', 'Spring'],
  }),
  makePerfume({
    code: 'W61',
    name: 'For Her Eau de Parfum (Pink Bottle)',
    brand: 'Narciso Rodriguez',
    gender: 'Female',
    accords: ['Musky', 'Rose', 'Powdery', 'Patchouli', 'Floral'],
    top: ['Rose', 'Peach'],
    middle: ['Musk', 'Amber'],
    base: ['Patchouli', 'Sandalwood'],
    longevity: '7-9 hours',
    sillage: 'Moderate to Strong',
    dayNight: 'Both',
    seasons: ['Autumn', 'Spring'],
  }),
  makePerfume({
    code: 'W62',
    name: 'Black Opium',
    brand: 'Yves Saint Laurent',
    gender: 'Female',
    accords: ['Coffee', 'Vanilla', 'Sweet', 'Warm Spicy', 'White Floral'],
    top: ['Pear', 'Pink Pepper', 'Orange Blossom'],
    middle: ['Coffee', 'Jasmine', 'Bitter Almond', 'Licorice'],
    base: ['Vanilla', 'Patchouli', 'Cashmere Wood', 'Cedar'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'W63',
    name: 'Hypnotic Poison',
    brand: 'Dior',
    gender: 'Female',
    accords: ['Vanilla', 'Almond', 'Sweet', 'White Floral', 'Warm Spicy'],
    top: ['Apricot', 'Plum', 'Coconut', 'Bergamot'],
    middle: ['Jasmine', 'Tuberose', 'Orange Blossom', 'Rose'],
    base: ['Vanilla', 'Almond', 'Sandalwood', 'Musk', 'Tonka Bean'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'U75',
    name: 'Hibiscus Mahajad',
    brand: 'Maison Crivelli',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Floral', 'Warm Spicy', 'Rose', 'Vanilla', 'Amber'],
    top: ['Hibiscus', 'Spearmint', 'Cassis'],
    middle: ['Damask Rose', 'Cinnamon'],
    base: ['Vanilla', 'Leather', 'Amber', 'Cedarwood'],
    longevity: '10+ hours',
    sillage: 'Enormous',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter', 'Spring'],
  }),
  makePerfume({
    code: 'U76',
    name: 'Oud Maracuja',
    brand: 'Maison Crivelli',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Tropical', 'Oud', 'Fruity', 'Leather', 'Woody'],
    top: ['Passionfruit', 'Fruity Notes', 'Turkish Rose', 'Saffron'],
    middle: ['Oud', 'Indonesian Patchouli', 'Benzoin'],
    base: ['Leather', 'Amber', 'Vanilla', 'Labdanum', 'Akigalawood'],
    longevity: '10+ hours',
    sillage: 'Enormous',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter', 'Spring'],
  }),
  makePerfume({
    code: 'U77',
    name: 'God of Fire',
    brand: 'Stephane Humbert Lucas 777',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Fruity', 'Tropical', 'Woody', 'Amber', 'Fresh'],
    top: ['Mango', 'Lemon', 'Pink Ginger', 'Red Berries'],
    middle: ['Coumarin', 'Jasmine', 'Dry Wood'],
    base: ['Oud', 'Nagarmotha', 'Musk', 'Amber'],
    longevity: '9-11 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Spring', 'Summer', 'Autumn'],
  }),
  makePerfume({
    code: 'U78',
    name: 'Erba Pura',
    brand: 'Xerjoff / Sospiro',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Fruity', 'Citrus', 'Sweet', 'Amber', 'Musky'],
    top: ['Sicilian Orange', 'Calabrian Bergamot', 'Sicilian Lemon'],
    middle: ['Fruity Basket (Mediterranean Fruits)'],
    base: ['White Musk', 'Amber', 'Madagascar Vanilla'],
    longevity: '10+ hours',
    sillage: 'Enormous',
    dayNight: 'Day',
    seasons: ['Spring', 'Summer'],
  }),
  makePerfume({
    code: 'U79',
    name: 'Eden Juicy Apple | 01',
    brand: 'Kayali',
    gender: 'Unisex',
    accords: ['Fruity', 'Sweet', 'Fresh', 'Berry', 'Floral'],
    top: ['Red Apple', 'Black Currant', 'Pink Grapefruit', 'Lychee'],
    middle: ['Wild Berries', 'Raspberry Blossom', 'Jasmine', 'Rose'],
    base: ['Sugar', 'Musk', 'Vanilla Flower', 'Amber', 'Moss'],
    longevity: '6-8 hours',
    sillage: 'Moderate',
    dayNight: 'Day',
    seasons: ['Spring', 'Summer'],
  }),
  makePerfume({
    code: 'U80',
    name: 'Imperial Valley',
    brand: 'Gissah',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Aromatic', 'Fresh Spicy', 'Woody', 'Amber', 'Leather'],
    top: ['Davana', 'Bergamot', 'Pink Pepper'],
    middle: ['Oud', 'White Amber', 'Rosemary'],
    base: ['Leather', 'Vetiver', 'Musk'],
    longevity: '9-11 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter', 'Spring'],
  }),
  makePerfume({
    code: 'U81',
    name: 'Shams Al Emarat',
    brand: 'Ard Al Zaafaran',
    gender: 'Unisex',
    accords: ['Sweet', 'Warm Spicy', 'Vanilla', 'Amber', 'Woody'],
    top: ['Vanilla', 'Green Apples'],
    middle: ['Spices', 'Rose'],
    base: ['Amber', 'Sandalwood', 'White Musk'],
    longevity: '7-9 hours',
    sillage: 'Moderate to Strong',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'U82',
    name: 'Baccarat Rouge 540',
    brand: 'Maison Francis Kurkdjian',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Amber', 'Woody', 'Warm Spicy', 'Fresh Spicy', 'Aromatic'],
    top: ['Saffron', 'Jasmine'],
    middle: ['Amberwood', 'Ambergris'],
    base: ['Fir Resin', 'Cedarwood'],
    longevity: '10+ hours',
    sillage: 'Enormous',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter', 'Spring'],
  }),
  makePerfume({
    code: 'U83',
    name: 'Vanilla Powder',
    brand: 'Matiere Premiere',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Vanilla', 'Powdery', 'Coconut', 'Sweet', 'Woody'],
    top: ['Palo Santo', 'Coconut Flakes'],
    middle: ['Bourbon Vanilla'],
    base: ['White Musk', 'Amberwood'],
    longevity: '9-11 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter', 'Spring'],
  }),
  makePerfume({
    code: 'U84',
    name: 'Gris Dior',
    brand: 'Dior (La Collection Privee)',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Mossy', 'Earthy', 'Rose', 'Citrus', 'Patchouli'],
    top: ['Bergamot', 'Citrus Accord'],
    middle: ['Rose', 'Jasmine'],
    base: ['Patchouli', 'Oakmoss', 'Amber', 'Cedar'],
    longevity: '8-10 hours',
    sillage: 'Moderate to Strong',
    dayNight: 'Both',
    seasons: ['Spring', 'Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'U85',
    name: 'Wild Vetiver',
    brand: 'Creed (Les Royales Exclusives / Vetiver Profile)',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Woody', 'Aromatic', 'Earthy', 'Fresh Spicy', 'Citrus'],
    top: ['Bergamot', 'Green Apple', 'Lemon'],
    middle: ['Vetiver', 'Pink Pepper', 'White Pepper'],
    base: ['Cedarwood', 'Musk', 'Ambergris'],
    longevity: '7-9 hours',
    sillage: 'Moderate',
    dayNight: 'Day',
    seasons: ['Spring', 'Summer', 'Autumn'],
  }),
  makePerfume({
    code: 'U86',
    name: 'Oud Royal / Oud Nacre',
    brand: 'Armani Prive',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Oud', 'Warm Spicy', 'Amber', 'Smoky', 'Woody'],
    top: ['Saffron', 'Incense'],
    middle: ['Agarwood (Oud)', 'Rose'],
    base: ['Amber', 'Sandalwood'],
    longevity: '10+ hours',
    sillage: 'Strong',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'U87',
    name: 'Starlight / Stillertime Profile',
    brand: 'Xerjoff (Spotlight / Starlight Profile)',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Warm Spicy', 'Cinnamon', 'Citrus', 'Woody', 'Sweet'],
    top: ['Cardamom', 'Bergamot'],
    middle: ['Cinnamon', 'Clove', 'Almond'],
    base: ['Amber', 'Cedarwood', 'Vanilla'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'U88',
    name: 'Ganymede',
    brand: 'Marc-Antoine Barrois',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Mineral', 'Leather', 'Warm Spicy', 'Woody', 'Citrus'],
    top: ['Mandarin Orange', 'Saffron'],
    middle: ['Violet Leaf', 'Osmathus'],
    base: ['Akigalawood', 'Immortelle', 'Mineral Notes', 'Suede'],
    longevity: '10+ hours',
    sillage: 'Enormous',
    dayNight: 'Both',
    seasons: ['Spring', 'Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'U89',
    name: 'Ombre Leather',
    brand: 'Tom Ford',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Leather', 'Warm Spicy', 'Earthy', 'Animalic', 'Smoky'],
    top: ['Cardamom'],
    middle: ['Leather', 'Jasmine Sambac'],
    base: ['Amber', 'Moss', 'Patchouli'],
    longevity: '9-11 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'U90',
    name: 'Guidance 46',
    brand: 'Amouage',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Woody', 'Floral', 'Nutty', 'Amber', 'Warm Spicy'],
    top: ['Pear', 'Frankincense', 'Hazelnut', 'Rose Water', 'Pink Pepper', 'Bitter Almond'],
    middle: ['Saffron', 'Rose', 'Jasmine Sambac', 'Osmanthus'],
    base: ['Sandalwood', 'Akigalawood', 'Ambergris', 'Vanilla', 'Labdanum', 'Georgywood'],
    longevity: '12+ hours',
    sillage: 'Enormous',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter', 'Spring'],
  }),
  makePerfume({
    code: 'U91',
    name: 'Ombre Nomade',
    brand: 'Louis Vuitton',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Oud', 'Smoky', 'Rose', 'Warm Spicy', 'Leather'],
    top: ['Incense', 'Raspberry'],
    middle: ['Rose', 'Saffron', 'Birch'],
    base: ['Agarwood (Oud)', 'Benzoin', 'Amberwood'],
    longevity: '12+ hours',
    sillage: 'Enormous',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'U92',
    name: 'Oud Bouquet',
    brand: 'Lancome',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Sweet', 'Oud', 'Vanilla', 'Warm Spicy', 'Woody'],
    top: ['Praline', 'Saffron'],
    middle: ['Rose', 'Petalia'],
    base: ['Agarwood (Oud)', 'Vanilla', 'Guaiac Wood'],
    longevity: '10+ hours',
    sillage: 'Strong',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'U93',
    name: 'Black Aoud',
    brand: 'Montale',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Rose', 'Oud', 'Patchouli', 'Musky', 'Warm Spicy'],
    top: ['Mandarin Orange', 'Rose'],
    middle: ['Cambodian Oud', 'Patchouli'],
    base: ['Musk', 'Labdanum'],
    longevity: '12+ hours',
    sillage: 'Enormous',
    dayNight: 'Night',
    seasons: ['Autumn', 'Winter'],
  }),
  makePerfume({
    code: 'U94',
    name: 'Delina',
    brand: 'Parfums de Marly',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Rose', 'Floral', 'Fruity', 'Fresh', 'Rhubarb'],
    top: ['Lychee', 'Rhubarb', 'Bergamot', 'Nutmeg'],
    middle: ['Turkish Rose', 'Peony', 'Musk', 'Petalia', 'Vanilla'],
    base: ['Cashmeran', 'Cedar', 'Vetiver', 'Incense'],
    longevity: '9-11 hours',
    sillage: 'Strong',
    dayNight: 'Day',
    seasons: ['Spring', 'Summer'],
  }),
  makePerfume({
    code: 'U95',
    name: "Love Don't Be Shy / Marshmallow Profile",
    brand: 'Kilian / Sweet Marshmallow Concept',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Sweet', 'Vanilla', 'White Floral', 'Citrus', 'Caramel'],
    top: ['Neroli', 'Bergamot', 'Pink Pepper', 'Coriander'],
    middle: ['Orange Blossom', 'Jasmine', 'Honeysuckle', 'Iris', 'Rose'],
    base: ['Sugar', 'Vanilla', 'Marshmallow', 'Caramel', 'Musk', 'Labdanum'],
    longevity: '8-10 hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter', 'Spring'],
  }),
  makePerfume({
    code: 'U96',
    name: "Angels' Share",
    brand: 'Kilian',
    gender: 'Unisex',
    category: 'Luxury Perfume',
    accords: ['Sweet', 'Vanilla', 'Amber', 'Woody', 'Warm Spicy'],
    top: ['Cognac', 'Cinnamon'],
    middle: ['Oak', 'Tonka Bean', 'Praline'],
    base: ['Vanilla', 'Sandalwood', 'Amber', 'Musk'],
    longevity: '10+ hours',
    sillage: 'Strong',
    dayNight: 'Both',
    seasons: ['Autumn', 'Winter'],
  }),
];
